return {
  -- A framework for interacting with tests within NeoVim.
  -- {
  --   'nvim-neotest/neotest',
  --   dependencies = {
  --     'nvim-neotest/nvim-nio',
  --     'nvim-lua/plenary.nvim',
  --     'antoinemadec/FixCursorHold.nvim',
  --     'nvim-treesitter/nvim-treesitter',
  --     'nvim-neotest/neotest-go',
  --   },
  --   config = function()
  --     -- get neotest namespace (api call creates or returns namespace)
  --     local neotest_ns = vim.api.nvim_create_namespace 'neotest'
  --     vim.diagnostic.config({
  --       virtual_text = {
  --         format = function(diagnostic)
  --           local message = diagnostic.message:gsub('\n', ' '):gsub('\t', ' '):gsub('%s+', ' '):gsub('^%s+', '')
  --           return message
  --         end,
  --       },
  --     }, neotest_ns)
  --
  --     local neotest = require 'neotest'
  --
  --     neotest.setup {
  --       adapters = {
  --         require 'neotest-go',
  --       },
  --     }
  --
  --     vim.keymap.set('n', '<leader>Tn', neotest.run.run, { desc = '[T]esting: run [n]earest test' })
  --     vim.keymap.set('n', '<leader>Tf', function()
  --       neotest.run.run(vim.fn.expand '%')
  --     end, { desc = '[T]esting: run test [f]ile' })
  --   end,
  -- },
}
